- clean: ['~']
- shell:
    # mutt
    -
        - ""
        - "You must install goobook to fetch/add contacts from Google\n\tex.: easy_install goobook"
    # git
    -
        - wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -N -P ~/.extras/
        - "Downloading GIT completion dependency"
    -
        - wget https://raw.githubusercontent.com/jonas/tig/master/contrib/vim.tigrc -N -P ~/.extras/
        - "Downloading TIG vim keybindings dependency"
    # powerline
    -
        - git clone --recursive https://github.com/powerline/powerline.git ~/downloads/GIT/powerline
        - "Cloning POWERLINE dependency (Run it afterwards: python setup.py build; powerline-daemon --replace)"
    # tmux plugin manager
    -
        - git clone --recursive https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
        - "Cloning TMUX PLUGIN MANAGER dependency (Reload tmux afterwards)"
    # solarized
    -
        - git clone --recursive https://github.com/altercation/solarized.git ~/downloads/GIT/solarized
        - "Cloning SOLARIZED dependency (FUCK YEAHHH!)"
    # oh-my-zsh
    -
        - git clone --recursive https://github.com/robbyrussell/oh-my-zsh.git ~/downloads/GIT/oh-my-zsh
        - "Cloning OH-MY-ZSH dependency (use antigen instead?)"
    # zsh-completions
    -
        - git clone --recursive https://github.com/zsh-users/zsh-completions ~/downloads/GIT/zsh-completions
        - "Cloning ZSH-COMPLETIONS dependency"
    # fasd
    -
        - git clone --recursive https://github.com/clvv/fasd.git ~/downloads/GIT/fasd
        - "Cloning FASD dependency"
    -
        - ln -s ~/downloads/GIT/fasd/fasd ~/.bin/fasd
        - "Linking 'fasd'"
    # s
    -
        - git clone --recursive https://github.com/haosdent/s ~/downloads/GIT/s
        - "Cloning S dependency"
    # Bear
    -
        - git clone --recursive https://github.com/rizsotto/Bear.git ~/downloads/GIT/Bear
        - "Cloning BEAR dependency (You should compile/install it afterwards)"
    # Vundle
    -
        - git clone --recursive https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
        - "Cloning VUNDLE dependency (Run it afterwards: vim +PluginInstall +qall)"
- link:
    # mutt
    ~/.mutt: mutt
    # i3wm
    ~/.i3: i3
    ~/.config/dunst: dunst
    # git
    ~/.gitconfig: gitconfig
    # mplayer
    ~/.mplayer: mplayer
    # powerline
    ~/.config/powerline: powerline
    # tmux
    ~/.tmux.conf: tmux.conf
    # Xresources
    ~/.Xresources: Xresources
    # profile, bashrc and zshrc
    ~/.profile: profile
    ~/.bashrc: bashrc
    ~/.zshrc: zshrc
    # vim and its bundles
    ~/.vimrc: vim/vimrc
    ~/.vim/bundles.vim:
        create: true
        path: vim/bundles.vim
    #~/.asoundrc: asoundrc
    ~/.pythonrc: pythonrc
    # tig
    ~/.tigrc: tigrc
