- clean: ['~']
- shell:
    # mutt
    -
        - ""
        - "You must install goobook to fetch/add contacts from Google\n\tex.: easy_install goobook"
    # git
    -
        - git clone --recursive https://github.com/git/git.git ~/downloads/GIT/git
        - "Cloning GIT dependency (check for alternatives)"
    -
        - ln -s ~/downloads/GIT/git/contrib/completion/git-prompt.sh ~/.git-prompt.sh
        - "Linking 'git-prompt.sh'"
    # powerline
    -
        - git clone --recursive https://github.com/powerline/powerline.git ~/downloads/GIT/powerline
        - "Cloning POWERLINE dependency (Run it afterwards: python setup.py build; powerline-daemon --replace)"
    # tmux plugin manager
    -
        - git clone --recursive https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
        - "Cloning TMUX PLUGIN MANAGER dependency (Reload tmux afterwards)"
    # solarized
    -
        - git clone --recursive https://github.com/altercation/solarized.git ~/downloads/GIT/solarized
        - "Cloning SOLARIZED dependency (FUCK YEAHHH!)"
    # oh-my-zsh
    -
        - git clone --recursive https://github.com/robbyrussell/oh-my-zsh.git ~/downloads/GIT/oh-my-zsh
        - "Cloning OH-MY-ZSH dependency (use antigen instead?)"
    # zsh-completions
    -
        - git clone --recursive https://github.com/zsh-users/zsh-completions ~/downloads/GIT/zsh-completions
        - "Cloning ZSH-COMPLETIONS dependency"
    # z
    -
        - git clone --recursive https://github.com/rupa/z ~/downloads/GIT/z
        - "Cloning Z dependency"
    # s
    -
        - git clone --recursive https://github.com/haosdent/s ~/downloads/GIT/s
        - "Cloning S dependency"
- link:
    # mutt
    ~/.mutt: mutt
    # i3wm
    ~/.i3: i3
    ~/.config/dunst: dunst
    # git
    ~/.gitconfig: gitconfig
    # mplayer
    ~/.mplayer: mplayer
    # powerline
    ~/.config/powerline: powerline
    # tmux
    ~/.tmux.conf: tmux.conf
    # Xresources
    ~/.Xresources: Xresources
    # profile, bashrc and zshrc
    ~/.profile: profile
    ~/.bashrc: bashrc
    ~/.zshrc: zshrc
