- clean: ['~']
- link:
    # mutt
    ~/.mutt: mutt
    # i3wm
    ~/.i3: i3
    ~/.config/dunst: dunst
- shell:
    # mutt
    -
        - ""
        - "You must install goobook to fetch/add contacts from Google\n\tex.: easy_install goobook"
