- clean: ['~']
- link:
    # i3wm
    ~/.config/i3/config:
        create: true
        path: i3/config
    ~/.config/i3/scripts:
        create: true
        path: i3/scripts
    # dunst
    ~/.config/dunst/dunstrc:
        create: true
        path: dunst/dunstrc
    # rofi
    ~/.config/rofi/config.rasi:
        create: true
        path: rofi/config.rasi
    ~/.config/rofi/themes:
        create: true
        path: rofi/themes
    ~/.config/rofi/color_template.rasi:
        create: true
        path: rofi/color_template.rasi
    # git
    ~/.gitconfig: gitconfig
    ~/.gitignore.global: gitignore.global
    # tmux
    ~/.config/tmux/tmux.conf:
        create: true
        path: tmux/tmux.conf
    # XCompose
    ~/.XCompose: XCompose
    # xinitrc
    ~/.xinitrc: xinitrc
    # xbindkeysrc
    ~/.xbindkeysrc: xbindkeysrc
    # profile and zshrc
    ~/.profile: profile
    ~/.zshrc: zshrc
    # neovim
    ~/.config/nvim/init.lua:
        create: true
        path: nvim/init.lua
    ~/.config/nvim/lua:
        create: true
        path: nvim/lua
    ~/.config/nvim/after:
        create: true
        path: nvim/after
    ~/.pythonrc: pythonrc
    # tig
    ~/.config/tig/config:
        create: true
        path: tig/config
    ~/.config/tig/theme.tigrc:
        create: true
        path: tig/theme.tigrc
    # polybar
    ~/.config/polybar/config:
        create: true
        path: polybar/config
    # xkb mappings
    ~/.config/xkb: xkb
    # alacritty
    ~/.config/alacritty/alacritty.yml:
        create: true
        path: alacritty/alacritty.yml
    ~/.config/alacritty/color_template.yml:
        create: true
        path: alacritty/color_template.yml
    # pipewire
    ~/.config/pipewire/pipewire.conf:
        create: true
        path: pipewire/pipewire.conf
    # zathura
    ~/.config/zathura/zathurarc:
        create: true
        path: zathurarc
    # podman
    ~/.config/containers/containers.conf:
        create: true
        path: podman/containers.conf
    ~/.config/containers/registries.conf:
        create: true
        path: podman/registries.conf
    # spotifyd
    ~/.config/spotifyd/spotifyd.conf:
        create: true
        path: spotifyd/spotifyd.conf
    # librewolf
    ~/.librewolf/librewolf.overrides.cfg:
        create: true
        path: librewolf/librewolf.overrides.cfg
    # neofetch
    ~/.config/neofetch/config.conf:
        create: true
        path: neofetch/config.conf
    # btop
    ~/.config/btop/btop.conf:
        create: true
        path: btop/btop.conf
    # picom
    ~/.config/picom.conf: picom.conf
    # scripts
    ~/.local/bin/udev-handler:
        create: true
        path: bin/udev-handler
- shell:
    # git
    -
        - git clone --recursive https://github.com/petervanderdoes/gitflow-avh.git ~/Downloads/GIT/gitflow-avh
        - "Cloning GITFLOW-AVH dependency"
    -
        - git clone --recursive https://github.com/petervanderdoes/git-flow-completion ~/Downloads/GIT/git-flow-completion
        - "Cloning GIT-FLOW-COMPLETION dependency"
    -
        - wget https://raw.githubusercontent.com/jonas/tig/master/contrib/vim.tigrc -N -P ~/.config/tig/
        - "Downloading TIG vim keybindings dependency"
    -
        - wget https://raw.githubusercontent.com/jonas/tig/master/contrib/git-flow.tigrc -N -P ~/.config/tig/
        - "Downloading TIG git-flow keybindings dependency"
    # tmux plugin manager
    -
        - git clone --recursive https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
        - "Cloning TMUX PLUGIN MANAGER dependency (Reload tmux afterwards)"
    # oh-my-zsh
    -
        - git clone --recursive https://github.com/robbyrussell/oh-my-zsh.git ~/Downloads/GIT/oh-my-zsh
        - "Cloning OH-MY-ZSH dependency (use antigen instead?)"
    # zsh-completions
    -
        - git clone --recursive https://github.com/zsh-users/zsh-completions ~/Downloads/GIT/zsh-completions
        - "Cloning ZSH-COMPLETIONS dependency"
    # zce.zsh
    -
     - git clone --recursive https://github.com/hchbaw/zce.zsh.git ~/Downloads/GIT/zce.zsh
     - "Cloning zce.zsh dependency"
    # base16 things
    -
        - git clone --recursive https://github.com/tinted-theming/base16-shell.git ~/Downloads/GIT/base16-shell
        - "Cloning base16-shell dependency"
    -
        - git clone --recursive https://github.com/tinted-theming/base16-xresources.git ~/Downloads/GIT/base16-xresources
        - "Cloning base16-xresources dependency"
    # powerlevel10k
    -
        - git clone --recursive https://github.com/romkatv/powerlevel10k.git ~/Downloads/GIT/powerlevel10k
        - "Cloning powerlevel10k dependency"
    # pyenv
    -
        - git clone https://github.com/pyenv/pyenv.git ~/Downloads/GIT/pyenv
        - "Cloning pyenv dependency"
    -
        - git clone https://github.com/pyenv/pyenv-virtualenv.git ~/Downloads/GIT/pyenv/plugins/pyenv-virtualenv
        - "Cloning pyenv-virtualenv dependency"
    -
        - git clone https://github.com/pyenv/pyenv-update.git ~/Downloads/GIT/pyenv/plugins/pyenv-update
        - "Cloning pyenv-update dependency"
    -
        - git clone https://github.com/pyenv/pyenv-ccache.git ~/Downloads/GIT/pyenv/plugins/pyenv-ccache
        - "Cloning pyenv-ccache dependency"
