- clean: ['~']
- link:
    # mutt
    #~/.mutt: mutt
    # i3wm
    ~/.i3: i3
    # dunst
    ~/.config/dunst: dunst
    # rofi
    ~/.config/rofi: rofi
    # git
    ~/.gitconfig: gitconfig
    ~/.gitignore.global: gitignore.global
    # tmux
    ~/.tmux.conf: tmux.conf
    # XCompose
    ~/.XCompose: XCompose
    # xinitrc
    ~/.xinitrc: xinitrc
    # xbindkeys
    ~/.xbindkeysrs: xbindkeysrc
    # profile, bashrc and zshrc
    ~/.profile: profile
    ~/.bashrc: bashrc
    ~/.zshrc: zshrc
    # neovim
    ~/.config/nvim/init.lua:
        create: true
        path: nvim/init.lua
    ~/.config/nvim/lua:
        create: true
        path: nvim/lua
    ~/.config/nvim/after:
        create: true
        path: nvim/after
    ~/.pythonrc: pythonrc
    # tig
    ~/.config/tig: tig
    # weechat
    #~/.weechat: weechat
    # polybar
    ~/.config/polybar: polybar
    # ranger
    ~/.config/ranger/rc.conf:
        create: true
        path: ranger/rc.conf
    # xkb mappings
    ~/.config/xkb: xkb
    # alacritty
    ~/.config/alacritty: alacritty
    # scripts
    ~/.local/bin/udev-handler:
        create: true
        path: bin/udev-handler
- shell:
    # mutt
    #-
    #    - ""
    #    - "You must install goobook to fetch/add contacts from Google\n\tex.: easy_install goobook"
    # git
    -
        - wget https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -N -P ~/.extras/
        - "Downloading GIT completion dependency"
    -
        - git clone --recursive https://github.com/petervanderdoes/gitflow-avh.git ~/downloads/GIT/gitflow-avh
        - "Cloning GITFLOW-AVH dependency"
    -
        - git clone --recursive https://github.com/petervanderdoes/git-flow-completion ~/downloads/GIT/git-flow-completion
        - "Cloning GIT-FLOW-COMPLETION dependency"
    -
        - wget https://raw.githubusercontent.com/jonas/tig/master/contrib/vim.tigrc -N -P ~/.config/tig/
        - "Downloading TIG vim keybindings dependency"
    -
        - wget https://raw.githubusercontent.com/jonas/tig/master/contrib/git-flow.tigrc -N -P ~/.config/tig/
        - "Downloading TIG git-flow keybindings dependency"
    # tmux plugin manager
    -
        - git clone --recursive https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
        - "Cloning TMUX PLUGIN MANAGER dependency (Reload tmux afterwards)"
    # oh-my-zsh
    -
        - git clone --recursive https://github.com/robbyrussell/oh-my-zsh.git ~/downloads/GIT/oh-my-zsh
        - "Cloning OH-MY-ZSH dependency (use antigen instead?)"
    # zsh-completions
    -
        - git clone --recursive https://github.com/zsh-users/zsh-completions ~/downloads/GIT/zsh-completions
        - "Cloning ZSH-COMPLETIONS dependency"
    # fasd
    -
        - git clone --recursive https://github.com/clvv/fasd.git ~/downloads/GIT/fasd
        - "Cloning FASD dependency"
    -
        - ln -s ~/downloads/GIT/fasd/fasd ~/.bin/fasd
        - "Linking 'fasd'"
    # s
    -
        - git clone --recursive https://github.com/haosdent/s ~/downloads/GIT/s
        - "Cloning S dependency"
    # Bear
    -
        - git clone --recursive https://github.com/rizsotto/Bear.git ~/downloads/GIT/Bear
        - "Cloning BEAR dependency (You should compile/install it afterwards)"
    # weechat
    #-
    #  - git clone --recursive https://github.com/weechat/scripts.git ~/downloads/GIT/weechat-scripts
    #  - "Cloning weechat-scripts dependency"
    #-
    #  - mkdir -p ~/.weechat/lua/autoload/; ln -s ~/downloads/GIT/weechat-scripts/lua/urlselect.lua ~/.weechat/lua/autoload/urlselect.lua
    #  - "Linking 'urlselect.lua'"
    #-
    #  - mkdir -p ~/.weechat/perl/autoload/; ln -s ~/downloads/GIT/weechat-scripts/perl/buffers.pl ~/.weechat/perl/autoload/buffers.pl
    #  - "Linking 'buffers.pl'"
    #-
    #  - mkdir -p ~/.weechat/perl/autoload/; ln -s ~/downloads/GIT/weechat-scripts/perl/highmon.pl ~/.weechat/perl/autoload/highmon.pl
    #  - "Linking 'highmon.pl'"
    #-
    #  - mkdir -p ~/.weechat/perl/autoload/; ln -s ~/downloads/GIT/weechat-scripts/perl/iset.pl ~/.weechat/perl/autoload/iset.pl
    #  - "Linking 'iset.pl'"
    #-
    #  - mkdir -p ~/.weechat/python/autoload/; ln -s ~/downloads/GIT/weechat-scripts/python/go.py ~/.weechat/python/autoload/go.py
    #  - "Linking 'go.py'"
    #-
    #  - mkdir -p ~/.weechat/python/autoload/; ln -s ~/downloads/GIT/weechat-scripts/python/lnotify.py ~/.weechat/python/autoload/lnotify.py
    #  - "Linking 'lnotify.py'"
    # zce.zsh
    -
      - git clone --recursive https://github.com/hchbaw/zce.zsh.git ~/downloads/GIT/zce.zsh
      - "Cloning zce.zsh dependency"
    # fzf
    -
      - git clone --recursive https://github.com/junegunn/fzf.git ~/downloads/GIT/fzf
      - "Cloning fzf dependency"
    # ranger
    -
      - ranger --copy-config=scope
      - "Setting up scope.sh (ranger)"
