repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.19.1
    hooks:
      - id: stylua
        name: StyLua
        args: [-f, nvim/.stylua.toml, "-"]
  - repo: https://github.com/lunarmodules/luacheck
    rev: v1.1.1
    hooks:
      - id: luacheck
        name: luacheck
        args: [--config, nvim/.luacheckrc, "-"]
