#!/bin/sh

# conky wrapper for use with i3
# reference: http://i3wm.org/docs/user-contributed/conky-i3bar.html

# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1}'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

# Now send blocks with information forever:
exec conky -c $HOME/.i3/conkyrc
